export const DISPATCH_STATE = {
  SEARCHING: "SEARCHING",
  OFFER_SENT: "OFFER_SENT",
  OFFER_ACKED: "OFFER_ACKED",
  WAITING_RESPONSE: "WAITING_RESPONSE",
  ACCEPTED: "ACCEPTED",
  EXPIRED: "EXPIRED"
};